services:
    php-cli:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
            args:
                COMPOSER_GITHUB_TOKEN: ${COMPOSER_GITHUB_TOKEN:-''}
        volumes:
            - .:/app
